### ISSUE TITLE
Erro na opção de status impactados

### ISSUE THREAD

**Issue by davidiasass** [Probesys/glpi-plugins-father#1]
The same unmarked impact status option is being updated.

Example.

When closing the parent ticket children tickets are also being closed even with the option disabled

I want to just flag the parent ticket option without any action on the ticket
![ticket pai](https://user-images.githubusercontent.com/22041652/44406185-60c05c80-a531-11e8-8304-5354e97bc525.PNG)

**Comment by cyrilus** [comment]
Hello 
But I can reproduce this with the last version could you try with the one i commit today
Thank
