### ISSUE TITLE
ISSUE: Solution in Child tickets

### ISSUE THREAD

**Issue by benshoes** [Probesys/glpi-plugins-father#2]
GLPI9.5.3
father plugin 1.2.0

Hi,
When I put a solution in the parent ticket, this solution is not written in the child tickets.
Otherwise it's ok to resolve the child tickets.
Best regards,

**Comment by philg38** [comment]
hi @benshoes ,
on the last version of the plgin ( GLPI10 compatible ), when you add a solution to the parent ticket, a solution is add too to the child tickets.
